	#This code was auto-generated by a handwritten compiler from scratch, with the source file in Pascal
	#@author Victor Gong
	#@version 2024/01/08 12:54:37
	
	.text
	.globl main

main:
	#Block
	#Number
	li $v0 2
	sw $v0 varf
	#Procedure Call: foo
	#Push parameters
	#Number
	li $v0 3
	subu $sp $sp 4
	sw $v0 ($sp)
	jal foo
	lw $t0 ($sp)
	addu $sp $sp 4
	sw $v0 varignore
	#Writeln
	#Variable: f
	la $t0 varf
	lw $v0 ($t0)
	move $a0 $v0
	li $v0 1
	syscall
	la $a0 newline
	li $v0 4
	syscall
	li $v0 10
	syscall
	#Procedure: foo
foo:
	#Push return value
	li $v0 0
	subu $sp $sp 4
	sw $v0 ($sp)
	#Push $ra
	subu $sp $sp 4
	sw $ra ($sp)
	#Push local variables
	#Procedure Call: bar
	#Push parameters
	#Local Variable: d
	lw $v0 8($sp)
	subu $sp $sp 4
	sw $v0 ($sp)
	#Variable: f
	la $t0 varf
	lw $v0 ($t0)
	lw $t0 ($sp)
	addu $sp $sp 4
	#BinOp: Add
	addu $v0 $t0 $v0
	subu $sp $sp 4
	sw $v0 ($sp)
	jal bar
	lw $t0 ($sp)
	addu $sp $sp 4
	sw $v0 varignore
	lw $ra ($sp)
	addu $sp $sp 4
	lw $v0 ($sp)
	addu $sp $sp 4
	jr $ra
	#Procedure: bar
bar:
	#Push return value
	li $v0 0
	subu $sp $sp 4
	sw $v0 ($sp)
	#Push $ra
	subu $sp $sp 4
	sw $ra ($sp)
	#Push local variables
	#Writeln
	#Local Variable: f
	lw $v0 8($sp)
	move $a0 $v0
	li $v0 1
	syscall
	la $a0 newline
	li $v0 4
	syscall
	lw $ra ($sp)
	addu $sp $sp 4
	lw $v0 ($sp)
	addu $sp $sp 4
	jr $ra
	
.data
	newline: .asciiz "\n"
	varf: .word	0
	varignore: .word	0
