	#This code was auto-generated by a handwritten compiler from scratch, with the source file in Pascal
	#@author Victor Gong
	#@version 2024/01/08 12:54:37
	
	.text
	.globl main

main:
	#Block
	#Number
	li $v0 3
	sw $v0 varn
	#Procedure Call: print
	#Push parameters
	#Number
	li $v0 5
	subu $sp $sp 4
	sw $v0 ($sp)
	jal print
	lw $t0 ($sp)
	addu $sp $sp 4
	sw $v0 varignore
	#Writeln
	#Variable: n
	la $t0 varn
	lw $v0 ($t0)
	move $a0 $v0
	li $v0 1
	syscall
	la $a0 newline
	li $v0 4
	syscall
	li $v0 10
	syscall
	#Procedure: print
print:
	#Push return value
	li $v0 0
	subu $sp $sp 4
	sw $v0 ($sp)
	#Push $ra
	subu $sp $sp 4
	sw $ra ($sp)
	#Push local variables
	#Writeln
	#Local Variable: n
	lw $v0 8($sp)
	move $a0 $v0
	li $v0 1
	syscall
	la $a0 newline
	li $v0 4
	syscall
	lw $ra ($sp)
	addu $sp $sp 4
	lw $v0 ($sp)
	addu $sp $sp 4
	jr $ra
	
.data
	newline: .asciiz "\n"
	varn: .word	0
	varignore: .word	0
